### ISSUE TITLE
"SyntaxError: invalid syntax File "get_links.py", line 102     

### ISSUE THREAD

**Issue by Isaaclipse** [harshibar/common-intern#7]
When I run get_links.py using $python get_links.py I get this syntax error...

  File "get_links.py", line 102
    link = f"https://www.glassdoor.com{link}"
                                            ^
SyntaxError: invalid syntax

What could be the issue?

**Comment by harshibar-youtube** [comment]
Hi! Are you running Python 3? This could be a backwards-compatibility issue with Python 2.

**Comment by harshibar** [comment]
Hey there! Are you using Python 3? This could be a Python 2 backwards-compatibility issue with f-strings.

**Comment by Isaaclipse** [comment]
Yes, Python 2.7. I'll try Python 3 and see.

Respectfully,
-Isaac Atif

**Comment by Isaaclipse** [comment]
That fixed it - thank you! I have another question however...

When filling in the dictionary in apply.py at line 22, how can I fill in lines 29 and 30 so they link to my correct resume pdf file? And is there a way to see the submitted data in these applications? I don't seem to be getting email confirmations on my applications...

-Isaac
